version: 2

jobs:
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: load latest
          command: |
            cd /opt/circleci/.pyenv
            git pull
      - run:
          name: install python 3.6.3
          command: |
            pyenv install 3.6.3
            pyenv global 3.6.3
      - run:
          name: sam build
          command: |
            pip install pipenv
            python -m venv venv
            source venv/bin/activate

            pip install aws-sam-cli

            sam build --use-container

workflows:
  version: 2
  aws-sam-build:
    jobs:
      - deploy-dev
