version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.1.0

jobs:
  test_local_invoke:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-api:
          template: template.yaml
          endpoint: hello
      - run:
          name: curl
          command: |
            curl -X GET http://127.0.0.1:3000/hello

workflows:
  integration-test_deploy:
    jobs:
      - test_local_invoke
