version: 2

jobs:
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: load latest
          command: |
            sudo apt update && sudo apt upgrade -y
            cd /opt/circleci/.pyenv
            git pull
      - run:
          name: install python 3.9.0
          command: |
            pyenv install 3.9.0
            pyenv global 3.9.0
      - run:
          name: sam build
          command: |
            pip install pipenv
            python -m venv venv
            source venv/bin/activate

            pipenv install

            sam build --use-container

workflows:
  version: 2
  aws-sam-build:
    jobs:
      - deploy-dev
